spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mr_dev
    username: mr_dev_user
    password: migue
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false